### ISSUE TITLE
PrintListWithComma Example Broken

### ISSUE THREAD

**Issue by michaellandi** [StubbleOrg/Stubble.Helpers#18]
Hi,

First off, thanks for a great library.  We've started to use it extensively and it performs great.

It seems that the example from the README "PrintListWithComma" does not work anymore.  I was looking to try to implement some helpers that require no arguments (for example, getting the current date).  I noticed that this example is returning an empty string, just like the helpers I was trying to implement.

```
var helpers = new Helpers()
    .Register("PrintListWithComma", (context) => string.Join(", ", context.Lookup<int[]>("List")));

var builder = new StubbleBuilder()
    .Configure(conf => conf.AddHelpers(helpers))
    .Build();

var res = builder.Render("List: {{PrintListWithComma}}", new { List = new[] { 1, 2, 3 } });

Assert.Equal("1, 2, 3", res); //res == ""
```

Versions:
Stubble: 1.4.12
Stubble.Helpers: 1.0.16-g81ee0be16b

**Comment by Romanx** [comment]
Whoops looks like we broke something.

Thanks for testing the library, we'll try work out what's going on and get a fix in tomorrow.

Also a great bug report so ♥️

**Comment by Romanx** [comment]
Hey thanks for submitting this.

I've just pushed a new build which makes it so that only registered helpers are considered as helper tags by name when parsing. This shouldn't affect anything but allows us to check if something should or shouldn't have arguments when parsing allowing us to be smarter.

The code sample on the readme was actually invalid but I think it's a fair use case so this now enables it.

Please let us know if you run into any issues!

**Comment by michaellandi** [comment]
Awesome, thanks @Romanx!  I've confirmed this working in `1.0.19-ged47efda4a`.
