### ISSUE TITLE
Helper not being matched with triple curly braces

### ISSUE THREAD

**Issue by vgrudenic** [StubbleOrg/Stubble.Helpers#32]
Using Stubble.Helpers 1.1.3 and Stubble.Core 1.10.8, I tried the basic example from readme.md.

However it seems helper isn't working when the template has triple braces:

    var culture = new CultureInfo("en-GB");
    var helpers = new Stubble.Helpers.Helpers()
        .Register("FormatCurrency", (HelperContext context, decimal count) => count.ToString("C", culture));

    var stubble = new StubbleBuilder()
        .Configure(conf => conf.AddHelpers(helpers))
        .Build();

    var basicTripleStache = stubble.Render("{{{Count}}}", new { Count = 100.26m });
    Assert.Equal("100.26", basicTripleStache);

    var withHelper = stubble.Render("{{FormatCurrency Count}}", new { Count = 100.26m });
    Assert.Equal("£100.26", withHelper);

    // this doesn't render anything
    var tripleStacheWithHelper = stubble.Render("{{{FormatCurrency Count}}}", new { Count = 100.26m });
    Assert.Equal("£100.26", tripleStacheWithHelper);

Am I doing something wrong, or this isn't supported?

**Comment by Romanx** [comment]
Hey!

Thanks for reporting this, we didn't implement escaping support for this tag by default which seems to have been an oversight.

I've created a PR converting the tag to be inline with the standard mustache tag so that `{{{` and `{{&` would escape the result of the helper. This is a breaking change so we're going to release this as a new major version. I'll try get that pushed out later today

**Comment by Romanx** [comment]
Hey, sorry for the delay. I just released this on nuget under version 2.0.1.

Please let us know if you have any issues!
